Bmwant/fix warning for imp
bottlepy/bottle pull request #1043
Opened 2018-02-27 15:50 UTC by bmwant

## Rationale
This PR addresses #1029 

## Changes
* Add pycache files to gitignore
* Remove deprecated `assertEquals` in tests
* Fix deprecation warning for `imp` module

## Testing
With 
```
$ python --version
Python 3.6.3
$ pip install bottle==0.12.13
$ python -W default
> import bottle
```
to reproduce warning
```
>>> import bottle
/home/user/.virtualenvs/bottle3.6.3/lib/python3.6/site-packages/bottle.py:38: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
Current version doesn't show this warning and tests are passing.

2018-02-27 15:56 UTC, bmwant commented
@defnull tests are green, could you please review?

2018-04-06 18:41 UTC, hartwork commented on test/test_resources.py
> +            expected_fp.close()
Looks good but does not belong in commit "Update deprecated from 2.7 assertEquals", in my opinion.

2018-04-06 18:43 UTC, hartwork commented on setup.py
> +)
If this reformatting is useful, my vote for pulling it out of commit "Fix import warning".

2018-04-06 19:49 UTC, bmwant commented
@hartwork ok, will only leave changes related to import warning. imo there is no harm to include style refactor here as well

2018-04-10 09:17 UTC, bmwant commented
@hartwork updated.

2021-12-30 20:01 UTC, n1ngu approved these changes

2021-12-31 12:07 UTC, n1ngu commented
It's been a while but I think this PR is just fine as it is now. No hurry until python-3.12 (eventual removal of the imp module?) but the warning is annoying.

Can this be merged @hartwork ?

2021-12-31 16:20 UTC, hartwork commented
@n1ngu the changes to `.gitignore` are still out of place. Other than that, my review here is from three years and I have stopped using bottle a long time ago, so I will unsubscribe from this pull request. Good luck though.

2022-01-01 14:31 UTC, octaprog7 commented
line 2060: self.module = sys.modules.setdefault(name, imp.new_module(name))

imp module deprecated since version 3.4: The imp module is deprecated in favor of importlib.

line 2060 must be replaced with the following two lines:

new line 1: module_spec = importlib.machinery.ModuleSpec(name, None)
new line 2: self.module = sys.modules.setdefault(name, importlib.util.module_from_spec(module_spec))

at the very top of the bottle.py file, add the line::
import importlib.util

2022-01-01 18:38 UTC, bmwant commented
@n1ngu @hartwork I can update this PR and revert unrelated changes (like `.gitignore` updates). Just let me know what still should be done within this PR.

2022-01-03 11:08 UTC, n1ngu commented
I think @octaprog7 has a better idea on what should be updated regarding the implementation.

Regarding stylistic changes, I agree the .gitignore file should be reverted. The style changes in the import instruction are debatable, because you are already changing that line. Yet, less changes will make your commit easier to review, now and in a long future whenever somebody reviews the file history.

Just my opinion. Now that hartwork quitted we'll need to draw the attention of another maintainer and see if this suffices.

2022-01-03 11:13 UTC, n1ngu commented on bottle.py
> -        os, re, tempfile, threading, time, warnings, weakref, hashlib
The most conservative change needed for this PR would probably be
```
import base64, cgi, email.utils, functools, hmac, itertools, mimetypes,\
        os, re, tempfile, threading, time, warnings, weakref, hashlib, \
        importlib.utils
```
depending on the linting configuration (line max width and whatnot)

2022-01-04 14:26 UTC, bmwant commented
@n1ngu I've update the code and left only relevant changes related to the `imp` module

2022-01-04 15:01 UTC, n1ngu requested changes

2022-10-24 09:03 UTC, bmwant commented
Looks like irrelevant change now, so closing

2022-10-24 09:03 UTC, closed without merging